auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka-1:29092,kafka-2:29092,kafka-3:29092
    metrics:
      port: 5084
      type: JMX
    name: Kafka
    properties: {}
    readOnly: false
