{
 "title": "Kafka Metrics",
 "description": "Dashboard for metrics jmx_exporter prometheus",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate, job)"
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_cluster_partition_replicascount{job=\"$job\"}, topic)"
   },
   {
    "name": "online_broker",
    "query": "query_result(count(up{job=~\"$job\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=~\"$job\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",topic=\"\"}[1m]))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{job=~\"$job\"}"
    },
    {
     "expr": "count(kafka_cluster_partition_replicascount{job=\"$job\"} <= 1)by(instance)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",topic=\"\"}[$__range]))",
     "legendFormat": "Total messages from ${__from:date:MM-DD hA} to ${__to:date:MM-DD hA}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kafka_network_socketserver_networkprocessoravgidlepercent{job=\"$job\",instance=~\"$broker\"}*100)",
     "legendFormat": "Network processor avg {{instance}}"
    }
   ]
  },
  {
   "title": "Request Handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gauge",
   "description": "If <= 0 is very idle",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - rate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count_total{job=\"$job\",instance=~\"$broker\"}[1m]) / 10000000",
     "legendFormat": "Request handler avg {{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "title": "Produce Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchFollow Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps", "label": "Message/s" }
   ],
   "targets": [
    {
     "expr": "sort(sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_totalproducerequests_total{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"Produce\",job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "Bps", "label": "In (-) / Out (+)" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
     "legendFormat": "Bytes Out [{{instance}}]"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
     "legendFormat": "Bytes In [{{instance}}]"
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Failed Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{job=~\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job=~\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnects Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total{job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperexpires_total{job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{job=\"$job\",instance=~\"$broker\"})by(instance)",
     "legendFormat": "Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "Isr Shrinks / Isr Expands Per Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "ops", "label": "Expands (-) / Shrinks (+)" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_replicamanager_isrshrinks_total{job=\"$job\",instance=~\"$broker\"}[1m]))",
     "legendFormat": "ISR Shrinks Per Sec"
    },
    {
     "expr": "sum (irate(kafka_server_replicamanager_isrexpands_total{job=\"$job\",instance=~\"$broker\"}[1m]))",
     "legendFormat": "ISR Expands Per Sec"
    }
   ]
  },
  {
   "title": "FetchFollower Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"FetchFollower\",job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_requests_total{request=\"FetchConsumer\",job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Fetch Purgatory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{job=\"$job\",delayedOperation=\"Fetch\",instance=~\"$broker\"})by(instance)",
     "legendFormat": "Broker {{instance}}"
    }
   ]
  },
  {
   "title": "Total Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "reqps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
     "legendFormat": "Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "Log Flush Stats Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_log_logflushstats_logflushrateandtimems_count_total{job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Producer Purgatory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{job=\"$job\",delayedOperation=\"Produce\",instance=~\"$broker\"})by(instance)",
     "legendFormat": "Broker {{instance}}"
    }
   ]
  },
  {
   "title": "Leader Election Rate Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_controller_controllerstats_leaderelectionrateandtimems_count_total{job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Leader Per Broker",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{job=~\"$job\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Disk Usage Segment Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_log_log_size{job=~\"$job\",instance=~\"$broker\"})by(instance))",
     "legendFormat": "Instance Broker:  {{instance}}"
    }
   ]
  },
  {
   "title": "Count Partition per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_server_replicamanager_partitioncount{job=~\"$job\"}) by (instance))",
     "legendFormat": "Instance Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Threads Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 150 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_used_bytes{job=\"$job\",instance=~\"$broker\"} )",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "s", "label": "Usage/s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$broker\"}[5m])",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 159 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$broker\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}