name: kafka-course-multi-node-cluster

services:
  kafka-1:
    image: confluentinc/cp-kafka:8.1.2
    restart: on-failure
    ports:
      - 9092:9092
      - 15083:15083
      - 15084:15084
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-1:29092,CONTROLLER://kafka-1:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_BROKER_RACK: "rack-1"
#      KAFKA_UNCLEAN_LEADER_ELECTION: true
      KAFKA_OPTS: >
        -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent-1.5.0.jar=15083:/opt/prometheus-jmx-exporter/kafka.yml
      KAFKA_JMX_OPTS: >
        -Dcom.sun.management.jmxremote.port=15084
        -Dcom.sun.management.jmxremote.rmi.port=15084
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=localhost
    volumes:
      - ./prometheus-jmx-exporter:/opt/prometheus-jmx-exporter

  kafka-2:
    image: confluentinc/cp-kafka:8.1.2
    restart: on-failure
    ports:
      - 9093:9093
      - 25083:25083
      - 25084:25084
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-2:29092,CONTROLLER://kafka-2:29093,PLAINTEXT_HOST://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-2:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_BROKER_RACK: "rack-2"
#      KAFKA_UNCLEAN_LEADER_ELECTION: true
      KAFKA_OPTS: >
        -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent-1.5.0.jar=25083:/opt/prometheus-jmx-exporter/kafka.yml
      KAFKA_JMX_OPTS: >
        -Dcom.sun.management.jmxremote.port=25084
        -Dcom.sun.management.jmxremote.rmi.port=25084
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=localhost
    volumes:
      - ./prometheus-jmx-exporter:/opt/prometheus-jmx-exporter

  kafka-3:
    image: confluentinc/cp-kafka:8.1.2
    restart: on-failure
    ports:
      - 9094:9094
      - 35083:35083
      - 35084:35084
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-3:29092,CONTROLLER://kafka-3:29093,PLAINTEXT_HOST://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-3:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_BROKER_RACK: "rack-3"
#      KAFKA_UNCLEAN_LEADER_ELECTION: true
      KAFKA_OPTS: >
        -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent-1.5.0.jar=35083:/opt/prometheus-jmx-exporter/kafka.yml
      KAFKA_JMX_OPTS: >
        -Dcom.sun.management.jmxremote.port=35084
        -Dcom.sun.management.jmxremote.rmi.port=35084
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=localhost
    volumes:
      - ./prometheus-jmx-exporter:/opt/prometheus-jmx-exporter

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8080:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml

  prometheus:
    image: prom/prometheus:v2.47.0
    restart: on-failure
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  grafana:
    image: grafana/grafana:13.0
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  grafana_data:
