security.protocol=SSL
ssl.truststore.location=./certs/client.truststore.jks
ssl.truststore.password=password
ssl.keystore.location=./certs/client.keystore.jks
ssl.keystore.password=password
ssl.key.password=password
